name: Byg et Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: shipping-service

    steps:
      - uses: actions/checkout@v4

      - name: Extract version from .csproj
        id: extract_version
        run: |
          VERSION=$(grep '<InformationalVersion>' ShippingServiceAPI/ShippingServiceAPI.csproj | sed -E 's/.*<InformationalVersion>(.*)<\/InformationalVersion>.*/\1/')
          echo "VERSION=$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build . \
            -f ShippingServiceAPI/Dockerfile \
            -t ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ steps.extract_version.outputs.version }}
