name: Build and Push Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker_image_pipeline:
    name: Build Docker image and push to Docker Hub
    runs-on: ubuntu-latest

    permissions:
      contents: read

    env:
      IMAGE_NAME: shipping-service
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -f ShippingServiceAPI/Dockerfile \
            -t ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest \
            ShippingServiceAPI

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.DOCKER_USER }}/${{ env.IMAGE_NAME }}:latest
